# Generated by Django 5.2.5 on 2025-08-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок блога", max_length=100, verbose_name="Заголовок блога"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Введите содержимое блога", null=True, verbose_name="Содержимое блога"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью(изображение) блога",
                        null=True,
                        upload_to="blog/photo",
                        verbose_name="Превью блога",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Укажите, опубликован ли блог", verbose_name="Опубликовано"
                    ),
                ),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0, help_text="Укажите количество просмотров", verbose_name="Счетчик просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
                "ordering": ["title", "is_published"],
            },
        ),
    ]
