# Generated by Django 5.2.5 on 2025-08-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Введите цену за покупку",
                max_digits=15,
                null=True,
                verbose_name="Цена за покупку",
            ),
        ),
    ]
