# Generated by Django 5.2.5 on 2025-08-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_views_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение продукта",
                null=True,
                upload_to="product/photo",
                verbose_name="Изображение продукта",
            ),
        ),
    ]
