# Generated by Django 4.2.2 on 2025-09-09 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
